name: flexibase-auth-stack
services:

  flexibase-db:
    image: mysql
    container_name: flexibase-db
    ports:
      - ${FLEXIBASE_DB_EXPOSE_PORT}:3306
    environment:
      - MYSQL_ROOT_USER: ${FLEXIBASE_ADMIN_USER}
      - MYSQL_DATABASE: ${FLEXIBASE_AUTH_DB}
    volumes:
      - flexibase-db-data:/var/lib/mysql
    restart: unless-stopped

  flexibase-auth:
    build: .
    container_name: flexibase-auth
    ports:
      - ${FLEXIBASE_EXPOSE_PORT}:5000
    environment:
      - FLEXIBASE_EXPOSE_PORT: ${FLEXIBASE_EXPOSE_PORT}
      - FLEXIBASE_AUTH_SECRET_KEY: ${FLEXIBASE_AUTH_SECRET_KEY}
      - FLEXIBASE_ADMIN_USER: ${FLEXIBASE_ADMIN_USER}
      - FLEXIBASE_ADMIN_PASSWORD: ${FLEXIBASE_ADMIN_PASSWORD}
    depends_on:
      - flexibase-db
    restart: unless-stopped
      
volumes:
  flexibase-db-data:

networks:
  default:
    name: flexibase-auth-network
